# Generated by Django 5.1.2 on 2024-11-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0002_leavestub_rejectedleave"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rejectedleave",
            name="student",
        ),
        migrations.RemoveField(
            model_name="leave",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="leave",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="LeaveStub",
        ),
        migrations.DeleteModel(
            name="RejectedLeave",
        ),
    ]
