# Generated by Django 5.1.3 on 2024-11-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0004_leave_approver_class_studentprofile_teacherprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="class_name",
        ),
        migrations.RemoveField(
            model_name="leave",
            name="name",
        ),
    ]
