# Generated by Django 4.2.13 on 2024-12-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_leave_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
